--- #YAML:1.0
name:               POE-Component-Daemon
version:            0.1300
abstract:           ~
author:
    - Philip Gwyn
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IPC::SysV:  1
    POE:        1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
