# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Daemon
version:      0.1005
version_from: Daemon.pm
installdirs:  site
requires:
    POE:                           0.3202
    POE::API::Peek:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
