--- #YAML:1.0
name:                POE-Component-Daemon
version:             0.1008
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    POE:                           1
    POE::API::Peek:                1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Philip Gwyn
