--- #YAML:1.0
name:               POE-Component-Daemon
version:            0.1100
abstract:           ~
author:
    - Philip Gwyn
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:             1
    POE::API::Peek:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
